# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5505a083791f3dbba5d920427ac81c44b04a79c899bed43bf003a9ef85c7f32e1ecde2c5c94e17e99e1fe74be484999371d0e71762646dbcaed2c6cea10e7337

test:
  secret_key_base: 606a340258eba08e513e1a526bf49aa8fa86ca3cb4d356e5c020e985c4a0376a26d7798c3c2a9dbf542c37b685dd8a7e068afc07d7847c843fcaca2cc1dbc3aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
